### ISSUE TITLE
flexi-stream not of type stream on ABCL

### ISSUE THREAD

**Issue by eugeneia** [edicl/flexi-streams#22]
Concatenating flexi-streams on ABCL leads to a type error.

ABCL 1.5.0
flexi-streams 1.0.15

```
CL-USER(3): (make-concatenated-stream (flexi-streams:make-flexi-stream
                                    (make-string-input-stream "foo")))

#<THREAD "interpreter" {34317C33}>: Debugger invoked on condition of type TYPE-ERROR
  org.armedbear.lisp.StandardObject@74751ac8 is not an input stream.
Restarts:
  0: TOP-LEVEL Return to top level.
```

**Comment by stassats** [comment]
It's a problem with ABCL.

**Comment by eugeneia** [comment]
Are you saying it is an ABCL bug? Is it known? Is there a ticket?

**Comment by stassats** [comment]
Yes. You'll have to figure that out on your own.

**Comment by avodonosov** [comment]
flexi-streams inherits from ABCL's implementation specific `gray-streams:fundamental-input-stream`. Apparently not all ABCL IO functions accpet such objects - in your example `make-concatenated-stream`. In this ticket http://abcl.org/trac/ticket/373 `make-two-way-stream` doesn't work. 

Search in ABCL issue tracker: http://abcl.org/trac/search?q=gray-streams

You may add your example to a relevant ticket.
