### ISSUE TITLE
Probably, an error in octets-to-string

### ISSUE THREAD

**Issue by ralcantaraperez** [edicl/flexi-streams#26]
I'm having an issue converting a string with octets-to-string:
`(octets-to-string #(13) :external-format '(:code-page :id 1252))`

In SBCL it raises this error condition:
`Invalid index 1 for (SIMPLE-VECTOR 1), should be a non-negative integer below 1.`

**Comment by stassats** [comment]
You need to pass it an unsigned-byte-8 vector.

**Comment by ralcantaraperez** [comment]
In the release **1.0.15** the function didn't raise an exception (it returned "^M"). The error condition raised now seems to be about accessing past the end of the vector.
