### ISSUE TITLE
Probably, an error in octets-to-string

### ISSUE THREAD

**Issue by ralcantaraperez** [edicl/flexi-streams#27]
I'm having an issue converting a string with octets-to-string:
`(octets-to-string #(13) :external-format '(:code-page :id 1252))`

In SBCL it raises this error condition:
`Invalid index 1 for (SIMPLE-VECTOR 1), should be a non-negative integer below 1.`

In the release **1.0.15** the function didn't raise an exception (it returned "^M"). The error condition raised now, seems to be about accessing past the end of the vector.

**Comment by stassats** [comment]
You need to use an unsigned-bytes 8 array, just as I said in the previous ticket.

**Comment by ralcantaraperez** [comment]
Sorry but, isn't `#(13)` an unsigned-byte array?

**Comment by stassats** [comment]
Nope, that's a T array.

**Comment by ralcantaraperez** [comment]
Sorry again, can you give me an example of a unsigned-byte array?

**Comment by ralcantaraperez** [comment]
I've tried this:
```
(flexi-streams:octets-to-string
  (make-array 1 :element-type '(unsigned-byte 8) :initial-element 13)
  :external-format '(:code-page :id 1252))
```
...and raises the same error:
```
debugger invoked on a SB-INT:INVALID-ARRAY-INDEX-ERROR in thread
#<THREAD "main thread" RUNNING {10005E85B3}>:
  Invalid index 1 for (SIMPLE-ARRAY (UNSIGNED-BYTE 8)
                       (1)), should be a non-negative integer below 1.
```

**Comment by stassats** [comment]
It's actually a different issue. You are using CRLF line endings and ending the line on 13.

**Comment by ralcantaraperez** [comment]
I thought it was a bug because in release 1.0.15 it returned "^M" instead of signaling an error condition.

Thanks.

**Comment by stassats** [comment]
I made it stop searching for LF at the end of a string. And you can actually use #(13)

**Comment by stassats** [comment]
It returned ^M in the past because it was compiled with (safety 0), masking the bug.
