### ISSUE TITLE
:POSITION/:BOUND broken on current Quicklisp version

### ISSUE THREAD

**Issue by phoe** [edicl/flexi-streams#44]
Preparation:

```lisp
CL-USER> (alexandria:write-byte-vector-into-file 
          (coerce #(0 1 2 3 4 5 6 7 8 9) '(vector (unsigned-byte 8)))
          #p"/tmp/bytes")
#(0 1 2 3 4 5 6 7 8 9)
```

Bug:

```lisp
CL-USER> (with-open-file (stream #p"/tmp/bytes" :element-type '(unsigned-byte 8)
                                                :direction :input)
           (let ((flexi-stream (flex:make-flexi-stream stream :position 0 :bound 4
                                                              :element-type '(unsigned-byte 8)))
                 (output (make-array 10 :initial-element 0)))
             (read-sequence output flexi-stream)
             output))
#(0 1 2 3 0 0 0 0 0 0)

CL-USER> (with-open-file (stream #p"/tmp/bytes" :element-type '(unsigned-byte 8)
                                                :direction :input)
           (let ((flexi-stream (flex:make-flexi-stream stream :position 4 :bound 8
                                                              :element-type '(unsigned-byte 8)))
                 (output (make-array 10 :initial-element 0)))
             (read-sequence output flexi-stream)
             output))
#(0 1 2 3 0 0 0 0 0 0)
```

In the last case, I expected `#(4 5 6 7 0 0 0 0 0 0)` instead.

**Comment by mfiano** [comment]
Can reproduce. It seems position is always 0 and bound is interpreted as the relative offset from the supplied position. Seems a little strange, and doesn't align with the docstring.

**Comment by stassats** [comment]
I don't see where this behavior is documented anywhere.

**Comment by phoe** [comment]
https://edicl.github.io/flexi-streams/#make-flexi-stream

![Zrzut ekranu z 2021-03-25 21-46-12](https://user-images.githubusercontent.com/15045546/112541305-8847c780-8db3-11eb-94b9-8bfa1c90f78e.png)

**Comment by stassats** [comment]
It doesn't say that it moves the position of the underlying stream.

**Comment by phoe** [comment]
What does it do, then, and why does it interact with `bound` in the way it does?

**Comment by stassats** [comment]
It gets incremented.

**Comment by phoe** [comment]
OK, let me approach the problem from another way.

I have a file with contents `#(0 1 2 3 4 5 6 7 8 9)`. I would like to get an open stream to that file that will only refer to the "slice" `#(2 3 4 5)` inside that file. What is the canonical way of achieving that via flexi-streams? Does it involve the `:bound` and `:position` arguments?

**Comment by stassats** [comment]
Call FILE-POSITION beforehand.

**Comment by stassats** [comment]
Or even (setf flexi:stream-file-position)

**Comment by phoe** [comment]
So like the following, I assume:

```lisp
CL-USER> (with-open-file (stream #p"/tmp/bytes" :element-type '(unsigned-byte 8)
                                                :direction :input)
           (let ((flexi-stream (flex:make-flexi-stream stream :position 4 :bound 8
                                                              :element-type '(unsigned-byte 8)))
                 (output (make-array 10 :initial-element 0)))
             (file-position stream 4)
             (read-sequence output flexi-stream)
             output))
#(4 5 6 7 0 0 0 0 0 0)
```

OK, this works. Thanks.

(`flex:stream-file-position` is unexported; `file-position` works just fine though.)

**Comment by stassats** [comment]
it's actually from gray streams. So file-position will dispatch to it keeping everything in sync.

**Comment by stassats** [comment]
Assuming you call it (file-position flexi-stream 4), no need to supply :position 4 then.
